#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: 改名测试
        run: |
          mkdir -p ./artifact/
          echo 123 > ./artifact/123.txt
          echo "::set-env name=FILENAME::$(echo "OpenWrt-firmware-`date -d "+8 hour" +%Y%m%d-%H%M%S`")"
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.FILENAME }}
          path: ./artifact/
