name: 测试

on: 
  push:
    branches: 
      - master
#  schedule:
#    - cron: 0 22 * * 1
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 校验本地文件
      uses: actions/checkout@master

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
